"""empty message

Revision ID: 034cb8bdbe79
Revises: 98f82b891773
Create Date: 2024-07-06 17:55:53.979396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034cb8bdbe79'
down_revision = '98f82b891773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organizations')
    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['orgId'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('organizations',
    sa.Column('orgId', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.userId'], name='organizations_created_by_fkey'),
    sa.PrimaryKeyConstraint('orgId', name='organizations_pkey'),
    sa.UniqueConstraint('orgId', name='organizations_orgId_key')
    )
    # ### end Alembic commands ###
